---
jobs:
- name: build-image
  public: true
  plan:
  - in_parallel:
    - get: baggageclaim-dockerfile
      trigger: true
    - get: golang-1.x
      trigger: true
    - get: baggageclaim
    - get: oci-build-task
  - task: build
    image: oci-build-task
    privileged: true
    file: baggageclaim/ci/build-image.yml
  - put: baggageclaim-ci-image
    params: {image: image/image.tar}
- name: baggageclaim
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: baggageclaim
      trigger: true
    - get: baggageclaim-ci-image
      passed: [build-image]
  - in_parallel:
    - task: unit-linux
      image: baggageclaim-ci-image
      privileged: true
      file: baggageclaim/ci/unit-linux.yml
    - task: unit-darwin
      file: baggageclaim/ci/unit-darwin.yml
    - task: unit-windows
      file: baggageclaim/ci/unit-windows.yml

resources:
- name: baggageclaim
  type: git
  source:
    uri: https://github.com/concourse/baggageclaim.git
    branch: add-image-building
- name: baggageclaim-dockerfile
  type: git
  source:
    uri: https://github.com/concourse/baggageclaim.git
    branch: add-image-building
    paths: [Dockerfile]
- name: baggageclaim-ci-image
  type: registry-image
  source:
    repository: concourse/baggageclaim-ci
    password: ((docker.password))
    username: ((docker.username))
- name: golang-1.x
  type: registry-image
  source:
    repository: golang
    tag: 1
- name: oci-build-task
  type: registry-image
  icon: docker
  source: {repository: vito/oci-build-task}
