---
jobs:
- name: baggageclaim
  public: true
  serial: true
  plan:
  - get: baggageclaim
    trigger: true
  - aggregate:
    - task: unit-linux
      privileged: true
      file: baggageclaim/ci/unit-linux.yml
    - task: unit-darwin
      file: baggageclaim/ci/unit-darwin.yml
    - task: unit-windows
      file: baggageclaim/ci/unit-windows.yml

resources:
- name: baggageclaim
  type: git
  source:
    uri: https://github.com/concourse/baggageclaim.git
    branch: master
